# Generated by Django 3.0.5 on 2020-12-26 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sentence", models.CharField(max_length=200)),
                (
                    "total_records",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "verified_records",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("filename", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "sentence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="handle_sentence.Sentence",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
